PRODUCTO_ID = 0
MARCA = 1
SUB_MARCA = 2
MODELO = 3
PRECIO = 4
EXISTENCIA = 5
FECHA_RESURTIDO = 6

COLUMNAS = ["PRODUCTO_ID", "MARCA", "SUB_MARCA", "MODELO", "PRECIO", "EXISTENCIA", "FECHA_RESURTIDO"]
